# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cache.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61\x63he.proto\x12\nswiftcache\"=\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x13\n\x0bttl_seconds\x18\x03 \x01(\x05\"\x1e\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\x0bGetResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\"\x19\n\nDelRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1e\n\x0b\x44\x65lResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\"\r\n\x0bPingRequest\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xf1\x01\n\x0c\x43\x61\x63heService\x12\x36\n\x03Set\x12\x16.swiftcache.SetRequest\x1a\x17.swiftcache.SetResponse\x12\x36\n\x03Get\x12\x16.swiftcache.GetRequest\x1a\x17.swiftcache.GetResponse\x12\x36\n\x03\x44\x65l\x12\x16.swiftcache.DelRequest\x1a\x17.swiftcache.DelResponse\x12\x39\n\x04Ping\x12\x17.swiftcache.PingRequest\x1a\x18.swiftcache.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETREQUEST']._serialized_start=27
  _globals['_SETREQUEST']._serialized_end=88
  _globals['_SETRESPONSE']._serialized_start=90
  _globals['_SETRESPONSE']._serialized_end=120
  _globals['_GETREQUEST']._serialized_start=122
  _globals['_GETREQUEST']._serialized_end=147
  _globals['_GETRESPONSE']._serialized_start=149
  _globals['_GETRESPONSE']._serialized_end=192
  _globals['_DELREQUEST']._serialized_start=194
  _globals['_DELREQUEST']._serialized_end=219
  _globals['_DELRESPONSE']._serialized_start=221
  _globals['_DELRESPONSE']._serialized_end=251
  _globals['_PINGREQUEST']._serialized_start=253
  _globals['_PINGREQUEST']._serialized_end=266
  _globals['_PINGRESPONSE']._serialized_start=268
  _globals['_PINGRESPONSE']._serialized_end=299
  _globals['_CACHESERVICE']._serialized_start=302
  _globals['_CACHESERVICE']._serialized_end=543
# @@protoc_insertion_point(module_scope)
