// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: cache.proto

#include "cache.pb.h"
#include "cache.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace swiftcache {

static const char* CacheService_method_names[] = {
  "/swiftcache.CacheService/Set",
  "/swiftcache.CacheService/Get",
  "/swiftcache.CacheService/Del",
  "/swiftcache.CacheService/Ping",
};

std::unique_ptr< CacheService::Stub> CacheService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CacheService::Stub> stub(new CacheService::Stub(channel, options));
  return stub;
}

CacheService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Set_(CacheService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Get_(CacheService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Del_(CacheService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Ping_(CacheService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CacheService::Stub::Set(::grpc::ClientContext* context, const ::swiftcache::SetRequest& request, ::swiftcache::SetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::swiftcache::SetRequest, ::swiftcache::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Set_, context, request, response);
}

void CacheService::Stub::async::Set(::grpc::ClientContext* context, const ::swiftcache::SetRequest* request, ::swiftcache::SetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::swiftcache::SetRequest, ::swiftcache::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, std::move(f));
}

void CacheService::Stub::async::Set(::grpc::ClientContext* context, const ::swiftcache::SetRequest* request, ::swiftcache::SetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::swiftcache::SetResponse>* CacheService::Stub::PrepareAsyncSetRaw(::grpc::ClientContext* context, const ::swiftcache::SetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::swiftcache::SetResponse, ::swiftcache::SetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Set_, context, request);
}

::grpc::ClientAsyncResponseReader< ::swiftcache::SetResponse>* CacheService::Stub::AsyncSetRaw(::grpc::ClientContext* context, const ::swiftcache::SetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CacheService::Stub::Get(::grpc::ClientContext* context, const ::swiftcache::GetRequest& request, ::swiftcache::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::swiftcache::GetRequest, ::swiftcache::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void CacheService::Stub::async::Get(::grpc::ClientContext* context, const ::swiftcache::GetRequest* request, ::swiftcache::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::swiftcache::GetRequest, ::swiftcache::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void CacheService::Stub::async::Get(::grpc::ClientContext* context, const ::swiftcache::GetRequest* request, ::swiftcache::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::swiftcache::GetResponse>* CacheService::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::swiftcache::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::swiftcache::GetResponse, ::swiftcache::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::swiftcache::GetResponse>* CacheService::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::swiftcache::GetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CacheService::Stub::Del(::grpc::ClientContext* context, const ::swiftcache::DelRequest& request, ::swiftcache::DelResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::swiftcache::DelRequest, ::swiftcache::DelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Del_, context, request, response);
}

void CacheService::Stub::async::Del(::grpc::ClientContext* context, const ::swiftcache::DelRequest* request, ::swiftcache::DelResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::swiftcache::DelRequest, ::swiftcache::DelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Del_, context, request, response, std::move(f));
}

void CacheService::Stub::async::Del(::grpc::ClientContext* context, const ::swiftcache::DelRequest* request, ::swiftcache::DelResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Del_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::swiftcache::DelResponse>* CacheService::Stub::PrepareAsyncDelRaw(::grpc::ClientContext* context, const ::swiftcache::DelRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::swiftcache::DelResponse, ::swiftcache::DelRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Del_, context, request);
}

::grpc::ClientAsyncResponseReader< ::swiftcache::DelResponse>* CacheService::Stub::AsyncDelRaw(::grpc::ClientContext* context, const ::swiftcache::DelRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDelRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CacheService::Stub::Ping(::grpc::ClientContext* context, const ::swiftcache::PingRequest& request, ::swiftcache::PingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::swiftcache::PingRequest, ::swiftcache::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void CacheService::Stub::async::Ping(::grpc::ClientContext* context, const ::swiftcache::PingRequest* request, ::swiftcache::PingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::swiftcache::PingRequest, ::swiftcache::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void CacheService::Stub::async::Ping(::grpc::ClientContext* context, const ::swiftcache::PingRequest* request, ::swiftcache::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::swiftcache::PingResponse>* CacheService::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::swiftcache::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::swiftcache::PingResponse, ::swiftcache::PingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::swiftcache::PingResponse>* CacheService::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::swiftcache::PingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

CacheService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CacheService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CacheService::Service, ::swiftcache::SetRequest, ::swiftcache::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CacheService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::swiftcache::SetRequest* req,
             ::swiftcache::SetResponse* resp) {
               return service->Set(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CacheService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CacheService::Service, ::swiftcache::GetRequest, ::swiftcache::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CacheService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::swiftcache::GetRequest* req,
             ::swiftcache::GetResponse* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CacheService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CacheService::Service, ::swiftcache::DelRequest, ::swiftcache::DelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CacheService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::swiftcache::DelRequest* req,
             ::swiftcache::DelResponse* resp) {
               return service->Del(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CacheService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CacheService::Service, ::swiftcache::PingRequest, ::swiftcache::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CacheService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::swiftcache::PingRequest* req,
             ::swiftcache::PingResponse* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
}

CacheService::Service::~Service() {
}

::grpc::Status CacheService::Service::Set(::grpc::ServerContext* context, const ::swiftcache::SetRequest* request, ::swiftcache::SetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CacheService::Service::Get(::grpc::ServerContext* context, const ::swiftcache::GetRequest* request, ::swiftcache::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CacheService::Service::Del(::grpc::ServerContext* context, const ::swiftcache::DelRequest* request, ::swiftcache::DelResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CacheService::Service::Ping(::grpc::ServerContext* context, const ::swiftcache::PingRequest* request, ::swiftcache::PingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace swiftcache

